apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose.yml convert
    kompose.version: 1.4.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: haproxy
  name: haproxy
spec:
  replicas: 1
  selector:
    io.kompose.service: haproxy
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: haproxy
    spec:
      containers:
      - image: ' '
        name: haproxy
        ports:
        - containerPort: 15672
        - containerPort: 5672
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          name: haproxy-claim0
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: haproxy-claim0
        persistentVolumeClaim:
          claimName: haproxy-claim0
          readOnly: true
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - haproxy
      from:
        kind: ImageStreamTag
        name: haproxy:1.7
    type: ImageChange
status: {}
