apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: haproxy
  name: haproxy
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: haproxy:1.7
    generation: null
    importPolicy: {}
    name: "1.7"
status:
  dockerImageRepository: ""
