apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose.yml convert
    kompose.version: 1.4.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq3
  name: rabbitmq3
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: rabbitmq3
status:
  loadBalancer: {}
