apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose.yml convert
    kompose.version: 1.4.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq2
  name: rabbitmq2
spec:
  replicas: 1
  selector:
    io.kompose.service: rabbitmq2
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rabbitmq2
    spec:
      containers:
      - command:
        - /usr/local/bin/cluster-entrypoint.sh
        env:
        - name: RABBITMQ_ERLANG_COOKIE
        image: ' '
        name: rabbitmq2
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/bin/cluster-entrypoint.sh
          name: rabbitmq2-claim0
      restartPolicy: Always
      volumes:
      - name: rabbitmq2-claim0
        persistentVolumeClaim:
          claimName: rabbitmq2-claim0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - rabbitmq2
      from:
        kind: ImageStreamTag
        name: rabbitmq2:3-management
    type: ImageChange
status: {}
