apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq2
  name: rabbitmq2
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: rabbitmq:3-management
    generation: null
    importPolicy: {}
    name: 3-management
status:
  dockerImageRepository: ""
